In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
## Define the vocabulary size
voc_size=10000

In [11]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [12]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8540, 5960, 7611, 5722],
 [8540, 5960, 7611, 9676],
 [8540, 3508, 7611, 6582],
 [9071, 6173, 624, 4773, 1526],
 [9071, 6173, 624, 4773, 4669],
 [9398, 8540, 2546, 7611, 3166],
 [1211, 9830, 3994, 4773]]

In [15]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [16]:
import numpy as np

In [17]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8540 5960 7611 5722]
 [   0    0    0    0 8540 5960 7611 9676]
 [   0    0    0    0 8540 3508 7611 6582]
 [   0    0    0 9071 6173  624 4773 1526]
 [   0    0    0 9071 6173  624 4773 4669]
 [   0    0    0 9398 8540 2546 7611 3166]
 [   0    0    0    0 1211 9830 3994 4773]]


In [18]:
## feature representation
dim=10

In [19]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 49ms/step


array([[[ 0.01346168,  0.03342358, -0.00852569,  0.04756046,
          0.03290885,  0.04078809,  0.01277275, -0.01900702,
         -0.03079245,  0.01533693],
        [ 0.01346168,  0.03342358, -0.00852569,  0.04756046,
          0.03290885,  0.04078809,  0.01277275, -0.01900702,
         -0.03079245,  0.01533693],
        [ 0.01346168,  0.03342358, -0.00852569,  0.04756046,
          0.03290885,  0.04078809,  0.01277275, -0.01900702,
         -0.03079245,  0.01533693],
        [ 0.01346168,  0.03342358, -0.00852569,  0.04756046,
          0.03290885,  0.04078809,  0.01277275, -0.01900702,
         -0.03079245,  0.01533693],
        [ 0.01555542,  0.02535348,  0.02214295, -0.03517405,
          0.03565406,  0.03897091, -0.00747851,  0.02621837,
          0.02594813, -0.00289985],
        [-0.04822186, -0.02785354,  0.04751677, -0.04468007,
          0.00375394,  0.04615134,  0.00028228,  0.0127431 ,
         -0.01181382,  0.00880007],
        [ 0.03741021, -0.02280285,  0.00951362, -0.0

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 8540, 5960, 7611, 5722])

In [23]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 28ms/step


array([[ 0.01346168,  0.03342358, -0.00852569,  0.04756046,  0.03290885,
         0.04078809,  0.01277275, -0.01900702, -0.03079245,  0.01533693],
       [ 0.01346168,  0.03342358, -0.00852569,  0.04756046,  0.03290885,
         0.04078809,  0.01277275, -0.01900702, -0.03079245,  0.01533693],
       [ 0.01346168,  0.03342358, -0.00852569,  0.04756046,  0.03290885,
         0.04078809,  0.01277275, -0.01900702, -0.03079245,  0.01533693],
       [ 0.01346168,  0.03342358, -0.00852569,  0.04756046,  0.03290885,
         0.04078809,  0.01277275, -0.01900702, -0.03079245,  0.01533693],
       [ 0.01555542,  0.02535348,  0.02214295, -0.03517405,  0.03565406,
         0.03897091, -0.00747851,  0.02621837,  0.02594813, -0.00289985],
       [-0.04822186, -0.02785354,  0.04751677, -0.04468007,  0.00375394,
         0.04615134,  0.00028228,  0.0127431 , -0.01181382,  0.00880007],
       [ 0.03741021, -0.02280285,  0.00951362, -0.00278363, -0.03494228,
        -0.04803821, -0.00094853, -0.03770548